import React, {Component,} from 'react';
import {Icon, Grid,Image, Container,Responsive, Button} from 'semantic-ui-react'
import {Link} from 'react-router-dom';



export default class ArticleContent extends Component {
    render() {
        
        return(

            <div style={{textAlign:'center'}}>
                <Grid  style={{color:"gray", textAlign:"center", alignContent:"center"}}>
                    <Grid.Row >
                        <Responsive>
                            <figure>
                                <Image src="https://miro.medium.com/max/2000/1*-T8oo_JoKkMxfnPKLt_Ciw.jpeg"></Image>
                                <Link><u style={{color:"gray", textAlign:"center"}}>Books</u></Link>
                            </figure>
                        </Responsive>
                        
                    </Grid.Row>
                </Grid>
                <Container fluid >
                    <div style={{marginLeft:"18%", marginRight:"18%", paddingBottom:"24px"}}>
                        <h1 style={{fontSize:"40px"}}>If You Only Read A Few Books In 2018, Read These</h1>
                    </div>
                <Responsive minWidth={800}>
                    
                   
                    <Grid style={{marginLeft:"18%", marginRight:"18%"}}>
                        <Grid.Row>
                               
                                    <Grid.Column width={2}>
                                        <Image avatar size="small" src="https://miro.medium.com/fit/c/96/96/0*oxw8NBp_Td0n3l4_.png"></Image>
                                    </Grid.Column>
                                    <Grid.Column width={6}>
                                        <div style={{fontWeight:"40"}}>
                                            Ryan Holiday <span style={{paddingLeft:"20px"}}><Button basic color="green" size="mini" >Follow</Button></span>
                                        </div>
                                        <div style={{color:"gray"}}>
                                            Jun 26 2018 - 10 min read
                                        </div>
                                    </Grid.Column>
                                    <Grid.Column width={5} floated="right" style={{alignContent:"bottom", paddingTop:"20px", marginBottom:"20px"}}>
                                        <div style={{float:"right", alignContent:"bottom"}}>
                                            <Link><Icon  name="twitter" color='black'></Icon></Link>
                                            <Link><Icon name="facebook" color='black'></Icon></Link>
                                            <Link><Icon  name="bookmark" color='black'></Icon></Link>
                                        </div>
                                    </Grid.Column>
                        </Grid.Row>
                    </Grid>
                </Responsive>
                    <Grid style={{marginLeft:"18%", marginRight:"18%"}}>
                        <Grid.Row>
                                <div style={{textAlign:'justify', fontSize:'1.3em'}}>
                                        <p>If you'd liked <a style={{color:'black', textDecoration:'underline'}} href="https://thoughtcatalog.com/ryan-holiday/2016/10/37-wise-life-changing-lessons-from-the-ancient-stoics/" target="#"> to be jerked around less</a>, provoked less, and <a style={{color:'black', textDecoration:'underline'}} href="https://thoughtcatalog.com/ryan-holiday/2015/02/33-ways-to-be-an-insanely-productive-happy-balanced-person/" ><u>more productive and inwardly focused</u></a>, where should you start?</p>

                                        <p>To me, the answer is obvious: by turning to wisdom. Below is a list of 21 books that will help lead you to a better, stronger 2018.</p>

                                        <hr />
                                        <p><a style={{color:'black', textDecoration:'underline'}} href="http://geni.us/okvZg" target="#">
                                            <strong><em>Deep Work: Rules for Focused Success in a Distracted World</em> 
                                            </strong></a><strong>by Cal Newport </strong>
                                            Media consumption went way up in 2017. For 
                                            <a style={{color:'black', textDecoration:'underline'}} href="http://observer.com/2016/11/want-to-really-make-america-great-again-stop-reading-the-news/" target="#">
                                                most of us</a>, 
                                                that meant happiness and productivity went way down. 
                                                The world is becoming noisier and will become more so every day. 
                                                If you cant cultivate the ability to have quiet, insightful, 
                                                deeply focused periods of productive work, youre going to get screwed. 
                                                This is a book that explains 
                                                <a style={{color:'black', textDecoration:'underline'}} href="https://thoughtcatalog.com/ryan-holiday/2016/02/31-ways-to-get-more-deep-work-accomplished/" target="#">
                                                how to cultivate and protect that skill</a>  
                                                the ability to do <em>deep work.
                                                    </em> I strongly urge you to begin this practice in 2018 if you want to get anything done or perform your best.</p>

                                        <p><a style={{color:'black', textDecoration:'underline'}} href="http://geni.us/yBTi" target="#"><strong><em>The Subtle Art of Not Giving a F*ck: A Counterintuitive Approach to Living a Good Life</em></strong> </a><strong>by Mark Manson </strong>To me, <a style={{color:'black', textDecoration:'underline'}} href="https://thoughtcatalog.com/ryan-holiday/2013/11/practical-philosophy/" target="#">practical philosophy</a> has always been the art knowing what to  and what <em>not</em> to  <em>give a fuck </em>about. Thats what Marks book is about. Its not about apathy. Its about cultivating indifference to things that dont matter. Be careful, as <a style={{color:'black', textDecoration:'underline'}} href="http://www.dailystoic.com/marcus-aurelius/" target="#">Marcus Aurelius warns</a>, not to give the little things more time and thought they deserved. Maybe looking back at this year reveals how much effort youve frittered away worrying about the trivial. If so, let 2018 be a year that you only devote energy to things that truly matter  get the important things right by ignoring the insignificant.</p>

                                        <p><a style={{color:'black', textDecoration:'underline'}} href="http://geni.us/2dAWHp" target="#"><strong><em>The Way to Love: The Last Meditations of Anthony de Mello</em></strong></a><strong> by Anthony de Mello </strong>Coach Shaka Smart recommended this little book (and its a little book, probably the smallest Ive ever read. It fits in your palm). But its an incredibly wise and helpful read. Written by a Catholic Priest whod lived in India, the book has this unusual convergence of eastern and western thought. One of my favorite lines: &ldquo;The question to ask is not &lsquo;Whats wrong with this person? but &lsquo;What does this irritation tell me about myself? I plan on regularly revisiting it throughout 2018.</p>

                                        <p><a style={{color:'black', textDecoration:'underline'}} href="http://geni.us/w024" target="#"><strong><em>But What If Were Wrong</em></strong></a><strong><em> </em>by Chuck Klosterman </strong>Its always good to remind ourselves that almost everything were certain about will probably be eventually proven wrong. Klostermans subtitle  Thinking About the Present As If It Were the Past  is a brilliant exercise for getting some perspective in 2018. Whether you think its going to be a year of radical change for the better or a horrible year of excesses of dangerous precedent, youre probably wrong. Youre probably not even in the ballpark. This book shows you why, not with lectures about politics, but with a bunch of awesome thought experiments about music, books, movies and science.</p>

                                        <p><a style={{color:'black', textDecoration:'underline'}} href="http://geni.us/Qug4dRa" target="#"><strong><em>Rules for Radicals: A Practical Primer for Realistic Radicals</em></strong></a> <strong>by Saul Alinsky </strong>If Hillary Clinton had remembered the lessons of Saul Alinsky (who she wrote her college thesis on), the election may have turned out differently. Why? A notorious strategist and community organizer, Alinsky was a die hard pragmatist, but he also knew how to tell a story and create a collective cause. He could work within the system but knew how to shake it up and generate attention. This book is a classic and woefully underrated. Whatever you set out to do in 2018, this book can provide you <a style={{color:'black', textDecoration:'underline'}} href="https://thoughtcatalog.com/ryan-holiday/2016/08/29-lessons-from-the-greatest-strategic-minds-who-ever-lived-fought-or-lead/" target="#">with strategic guidance</a> and insight.</p>

                                        <p><a style={{color:'black', textDecoration:'underline'}} href="http://geni.us/92nBU" target="#"><strong><em>The Filter Bubble</em></strong></a><strong> by Eli Pariser</strong> / <a style={{color:'black', textDecoration:'underline'}} href="http://geni.us/lHK45" target="#"><strong><em>Trust Me Im Lying</em></strong></a><strong> by Ryan Holiday</strong> / <a style={{color:'black', textDecoration:'underline'}} href="http://geni.us/9RIF" target="#"><strong><em>The Brass Check</em></strong></a><strong> by Upton Sinclair </strong>I strongly recommend that you take the time in 2018 to read these books. In light of this year, you owe it to yourself to study and better understand how our media system works. In <em>The Filter Bubble</em>, Eli Pariser warns of the danger of living in bubbles of personalization that reinforce and insulate our worldview. Though Sinclairs <em>The Brass Check</em> has been almost entirely forgotten by history, its not only fascinating but a timeless perspective. Sinclair deeply understood the economic incentives of early 20th century journalism and thus could predict and analyze the manipulative effect it had on The Truth. I used that book as a model for my expose of the media system, <em>Trust Me, Im Lying</em>. Today, the incentives and pressures are different but they warp our information in a similar way. In almost every substantial charge Upton leveled against the yellow press, you could, today, sub in blogs and the cable news cycle and be even more correct.</p>

                                        <p><a style={{color:'black', textDecoration:'underline'}} href="http://geni.us/eZGfRP" target="#"><strong><em>48 Laws of Power</em></strong></a><strong> / </strong><a style={{color:'black', textDecoration:'underline'}} href="http://geni.us/xSOT" target="#"><strong><em>33 Strategies of War</em> </strong></a><strong>by Robert Greene </strong>Robert Greene is a master of human psychology and human dynamics  he has a profound ability to explain timeless truths through story and example. You can read the classics and not always understand the lessons. But if you read Roberts books, I promise you will leave not just with actionable lessons but an indelible sense of what to do in many trying and confusing situations. I <a style={{color:'black', textDecoration:'underline'}} href="https://thoughtcatalog.com/ryan-holiday/2016/08/29-lessons-from-the-greatest-strategic-minds-who-ever-lived-fought-or-lead/" target="#">wrote earlier this year</a> that strategic wisdom is not something we are born with  but the lessons are there for us to pick up. Pick these two up before the year ends and operate the next with a strategic mindset and clarity.</p>

                                        <p><a style={{color:'black', textDecoration:'underline'}} href="http://geni.us/Fs1JQZ" target="#"><strong><em>Conspiracy: Peter Thiel, Hulk Hogan, Gawker, and the Anatomy of Intrigue</em></strong></a><strong> by Ryan Holiday </strong> If you want to immerse yourself in the above topics of media and strategy, and are looking for one book to teach you lessons in both, my book on the nearly decade-long conspiracy that billionaire Peter Thiel waged against Gawker will do this for you. This is a stunning story about how power works in the modern age, and is a masterclass in strategy and how to accomplish wildly ambitious aims.</p>

                                        <p><a style={{color:'black', textDecoration:'underline'}} href="http://geni.us/pmrK" target="#"><strong><em>The Road To Character</em></strong></a> <strong>by David Brooks </strong>When General Stanley McChrystal <a style={{color:'black', textDecoration:'underline'}} href="http://fourhourworkweek.com/2015/07/10/general-stanley-mcchrystal-on-anti-war-americans-pushing-your-limits-and-the-three-military-tests-you-should-take/" target="#">was asked on the Tim Ferriss podcast</a>what was a recent purchase that had most positively impacted his life, he pointed to this book. I agree. It can be a bit stilted and dense at times, but it should be assigned reading to any young person today (a little challenge is a good thing). Illustrating with examples and stories from great men and women, Brooks admonishes the reader to undertake their own journey of character perfection. In <a style={{color:'black', textDecoration:'underline'}} href="http://www.amazon.com/Ego-Is-Enemy-Ryan-Holiday/dp/1591847818?tag=thougcatal0c-20" target="#">my own book</a>, I explore the same topic (humility) from a different angle using similar stories  Im <a style={{color:'black', textDecoration:'underline'}} href="https://thoughtcatalog.com/ryan-holiday/2016/06/25-ways-to-kill-the-toxic-ego-that-will-ruin-your-life/" target="#">attacking ego</a>, hes building up character. Both will be important for the next year.</p>

                                        <p><a style={{color:'black', textDecoration:'underline'}} href="http://geni.us/eNHHr" target="#"><strong><em>The Dip</em></strong></a><strong><em> </em>by Seth Godin </strong>This book is a short 70 pages and it looks like something someone would give as a joke gift, but its anything but. Godin talks frankly about quitting and pushing through  and when to do each. Quit when youll be mediocre, when the returns arent worth the investment, when you no longer think youll enjoy the ends. Stick when the dip is the obstacle that creates scarcity, when youre simply bridging the gap between beginners luck and mastery. I promise, next year you are guaranteed to find yourself in moments when you dont know what is the right answer. This book will help you find it.</p>

                                        <p><a style={{color:'black', textDecoration:'underline'}} href="http://geni.us/lIKYItr" target="#"><strong><em>Hillbilly Elegy: A Memoir of a Family and Culture in Crisis</em></strong></a><strong> by J. D. Vance</strong> / <a style={{color:'black', textDecoration:'underline'}} href="http://geni.us/Gvnh4JE" target="#"><strong><em>Strangers in Their Own Land: Anger and Mourning on the American Right</em> </strong></a><strong>by Arlie Russell Hochschild </strong>You might describe <em>Hillbilly Elegy</em> as <a style={{color:'black', textDecoration:'underline'}} href="http://observer.com/2015/07/why-ta-nehisi-coatess-between-the-world-and-me-is-not-the-masterpiece-we-hoped-for/" target="#">a Ta-Nehisi Coates style memoir</a> about a community that  at least in progressive circles  gets a lot less attention: disaffected, impoverished whites (particularly in the mid-east and South). I thought the book was empathetic, self-aware and inspiring. The author pokes some holes in the concept of &ldquo;white privilege&rdquo;  certainly a third or fourth generation hillbilly in Kentucky doesnt walk around feeling like they have it easy  and an explanation of some of the <a style={{color:'black', textDecoration:'underline'}} href="https://thoughtcatalog.com/ryan-holiday/2016/08/dear-dad-here-are-49-more-reasons-why-you-shouldnt-vote-for-donald-trump/" target="#">phenomenon behind Donald Trump</a> (notice I said explanation, not an excuse). This is a sober but also hopeful book. I urge people on all sides of the political spectrum to read it, but progressives would benefit from the eye-opening perspective the most. Pair it with <em>Strangers in Their Own Land,</em> the author of which, a Berkeley native, visits and interviews people in the deep Louisiana countryside. (Remember: you dont have to agree with the people youre reading about  but you should care what makes them tick.)</p>

                                        <p><a style={{color:'black', textDecoration:'underline'}} href="http://geni.us/ebD7KV" target="#"><strong><em>It Cant Happen Here</em></strong></a> <strong>by Sinclair Lewis </strong>This book is one that will make you so uncomfortable that youll probably pick it up and put it down several times. It almost shocks you that this exists, that its not some work of fiction pretending to be 80 years old. But no, in fact, one of Americas most famous writers wrote a bestselling book about an appalling populist demagogue who won the presidency of the United States. Europe was a mess, the economy was in the toilet. Well meaning people talked earnestly about the need for &ldquo;serious change&rdquo; and &ldquo;revolution.&rdquo; The parties split, and a fringe candidate suddenly becomes viable. When people tried to question some of the ideas he campaigned on, they were shouted down: &ldquo;This is how all politicians speak. Hes not serious about that extreme stuff.&rdquo; Life imitates art and now, <em>this is what actually happened.</em> Change the dates, places and names and its no longer fiction, its real. Fiction is best when it puts a mirror up to us. This book does that. If you dont read the book, <a style={{color:'black', textDecoration:'underline'}} href="https://en.wikipedia.org/wiki/It_Can%27t_Happen_Here" target="#">at least please read about it</a>. Because you need to know. It can happen here.</p>

                                        <p><a style={{color:'black', textDecoration:'underline'}} href="http://geni.us/l1mXsAf" target="#"><strong><em>How to Live: Or A Life of Montaigne in One Question and Twenty Attempts at an Answer</em></strong></a><strong> by Sarah Bakewell </strong>The book is spectacular. It was a bestseller in the UK and was featured in a <a style={{color:'black', textDecoration:'underline'}} href="https://www.theguardian.com/commentisfree/belief/2010/may/10/montaigne-philosophy" target="#">6 part series in <em>The Guardian</em></a>. The format of the book is a bit unusual, instead of chapters it is made up of 20 Montaigne style essays that discuss the man from a variety of different perspectives. Montaigne was a man obsessed with figuring himself out  why he thought the way he did, how he could find happiness, his fetishes, his near-death experiences. He lived in tumultuous times too and he coped by looking inward. Were lucky he did, and we can do the same.</p>

                                        <p><a style={{color:'black', textDecoration:'underline'}} href="http://geni.us/f3YO" target="#"><strong><em>Tribe: On Homecoming and Belonging</em></strong></a><strong> by Sebastian Junger </strong>Junger looks at many of the social issues we have today: PTSD. Depression. Political polarization. Contempt for our fellow citizens. Aimlessness. Weve lost the bonds that tie a tribe and culture together. No wonder veterans feel alone and lost when they leave their tight knit tribe and re-enter solitary civilian life. No wonder <em>many</em>people feel that way regardless of whether they served or not. No wonder we have trouble agreeing on basic solutions to common problems. There is <a style={{color:'black', textDecoration:'underline'}} href="http://observer.com/2016/12/we-are-living-in-a-post-shame-world-and-thats-not-a-good-thing/" target="#">no sense of what is common or basic or shared</a>. Given the divisiveness that we are facing as a society  that became painfully clear in 2016  this is one of the most urgent and important book you need to read next year.</p>

                                        <p><a style={{color:'black', textDecoration:'underline'}} href="http://geni.us/CHh4o" target="#"><strong><em>The Years of Lyndon Johnson</em> (4 Volumes)</strong></a><strong> by Robert A. Caro </strong>In January of 2016, I picked up my first book in this Caros series on Lyndon Johnson. It wasnt until June that I finished my fourth, but I consider finishing all (~3,500 pages) of them to be <a style={{color:'black', textDecoration:'underline'}} href="https://thoughtcatalog.com/ryan-holiday/2016/01/did-you-actually-read-that-the-joy-of-reading-really-really-long-books/?utm_source=Ryan+Holiday+List&amp;utm_campaign=fe3d96da3c-EMAIL_CAMPAIGN_2016_12_11&amp;utm_medium=email&amp;utm_term=0_f7f33084e9-fe3d96da3c-415543949" target="#">one of my proudest reading achievements</a>. If there is one line that sums up the whole series its this: Its that power doesnt only corrupt. Thats too simple. What power does is <em>reveal.</em> Its also easy to be disillusioned by politics right now but for me, getting lost in these Lyndon Johnson books has been a helpful and educational process. Because you learn two things 1) that things have always been complicated and confusing but they tend to turn out alright 2) that our system, whatever its flaws, can still produce good results from bad men. And without a doubt, thats a good reminder to have on the eve of 2018.</p>

                                        <p><a style={{color:'black', textDecoration:'underline'}} href="http://geni.us/fzsxbS" target="#"><strong><em>The Last Lion: Winston Spencer Churchill</em> (3 Volumes)</strong></a><strong> by William Manchester </strong>Dont think an individual can make a difference in history? Then you havent read enough about Winston Churchill. The scenes in this book: warning about the looming threat of Nazism, the retreat at Dunkirk, persevering through the Blitz, vowing to fight on the landing grounds and the beaches and in the streets, whatever the cost may be. The sheer determination of this man, to take an entire country on your back and defy a horde which had overrun the European continent in a matter of months&hellip;its almost breathtaking to think about. (If you were to only read <em>one</em> thing in the next year, you could do a lot worse than either of these series. They contain dozens of books within them and will teach you about so much more than just the man they are ostensibly about. Please, please read them.)</p>

                                        <p><a style={{color:'black', textDecoration:'underline'}} href="http://geni.us/9AeK" target="#"><strong><em>Mr. Eternity</em></strong></a><strong> by Aaron Thier / </strong><a style={{color:'black', textDecoration:'underline'}} href="http://geni.us/JEWdH" target="#"><strong><em>The Count of Monte Cristo</em></strong></a><strong> by Alexandre Dumas </strong>These books really have nothing to do with the events of 2016 but they are long and entertaining and they will make you forget your problems for the next 12 months. I thought Id read Monte Cristo as a kid, but clearly I didnt. Because the actual book is a 1,200 page epic of some of the most brilliant, beautiful and complicated storytelling ever put to paper. What a book! When I typed out my notes (and quotes) after finishing this book, it ran some 3,000 words. As for <em>Mr. Eternity</em>, its a fun, epic jaunt through the distant future (as though it was the past) in the vein of Voltaires <a style={{color:'black', textDecoration:'underline'}} href="http://geni.us/GgDN" target="#"><em>Candide</em></a>. <em>Candide</em> isnt a bad read for this year either: &ldquo;We must cultivate our own garden.&rdquo;</p>

                                        <h1>Like to Read?</h1>

                                        <p>Ive created a list of 15 books <strong>youve never heard of </strong>that will alter your worldview and help you excel at your career.</p>

                                        <p><a style={{color:'black', textDecoration:'underline'}} href="https://mailchi.mp/ryanholiday.net/15books" target="#">Get the secret book list here!</a></p>

                                        <hr />
                                        <p><em>This originally appeared on </em><a style={{color:'black', textDecoration:'underline'}} href="https://thoughtcatalog.com/ryan-holiday/2016/12/if-you-only-read-a-few-books-in-2017-read-these/" target="#"><em>Thought Catalog</em></a><em>.</em></p>
                                </div>
                        </Grid.Row>
                    </Grid>
                </Container>
            </div>
        )
    }
}